services:
  web:
    image: ${DOCKER_IMAGE_REGISTRY}/entrysport:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_GA_MEASUREMENT_ID: ${NEXT_PUBLIC_GA_MEASUREMENT_ID}
        NEXT_PUBLIC_CULQI_PUBLIC_KEY: ${NEXT_PUBLIC_CULQI_PUBLIC_KEY}
        NEXT_PUBLIC_CULQI_ORDER_ID: ${NEXT_PUBLIC_CULQI_ORDER_ID}
        NEXT_PUBLIC_CULQI_RSA_ID: ${NEXT_PUBLIC_CULQI_RSA_ID}
        NEXT_PUBLIC_CULQI_RSA_PUBLIC_KEY: ${NEXT_PUBLIC_CULQI_RSA_PUBLIC_KEY}
        NEXT_PUBLIC_CULQI_TITLE: ${NEXT_PUBLIC_CULQI_TITLE}
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
      POSTGRES_URL_NON_POOLING: ${POSTGRES_URL_NON_POOLING}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - ./public:/app/public
  nginx:
    image: nginx:1.29-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/www/production/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-webroot:/var/www/html
    environment:
      SSL_DOMAIN_1: ${SSL_DOMAIN_1}
    depends_on:
      - web
volumes:
  certbot-etc:
  certbot-webroot:
